FROM rockylinux:9

RUN dnf install -y openssh-server sudo python3 && ssh-keygen -A

RUN useradd -m -s /bin/bash -G wheel ansible
RUN echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN mkdir -p /home/ansible/.ssh \
 && chmod 700 /home/ansible/.ssh \
 && chown ansible:ansible /home/ansible/.ssh

COPY keys/ansible_key.pub /home/ansible/.ssh/authorized_keys

RUN chmod 600 /home/ansible/.ssh/authorized_keys \
 && chown ansible:ansible /home/ansible/.ssh/authorized_keys

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]