FROM ubuntu:22.04

RUN apt-get update && apt-get install -y openssh-server sudo python3
RUN useradd -m -s /bin/bash -G sudo ansible

RUN mkdir -p /home/ansible/.ssh \
 && chmod 700 /home/ansible/.ssh \
 && chown ansible:ansible /home/ansible/.ssh
RUN echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
COPY keys/ansible_key.pub /home/ansible/.ssh/authorized_keys
RUN chmod 600 /home/ansible/.ssh/authorized_keys \ && chown ansible:ansible /home/ansible/.ssh/authorized_keys
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]